
export interface PerformanceStats {
  fps: number;
  drawCalls: number;
  triangles: number;
  geometries: number;
  textures: number;
  entities: number;
}

export interface BoidsParams {
  speed: number;
  separationRadius: number;
  separationStrength: number;
  alignmentRadius: number;
  cohesionRadius: number;
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
  timestamp: string;
}

export interface Broadcast {
  id: string;
  headline: string;
  detail: string;
  sentiment: -1 | 0 | 1;  // -1 bear, 0 neutral, +1 bull
  tokens: string[];         // tokens most affected
  category: 'bull' | 'bear' | 'fud' | 'hopium' | 'airdrop' | 'regulation' | 'tech' | 'macro';
  timestamp: number;
}

export type PostCategory =
  | 'trade'
  | 'investment'
  | 'prediction'
  | 'shill'
  | 'coin-launch'
  | 'ponzi-alert'
  | 'scam-warning'
  | 'fundraising'
  | 'begging'
  | 'collaboration'
  | 'strategy'
  | 'token-launch'
  | 'news'
  | 'alpha'
  | 'advertisement'
  | 'meme'
  | 'rug-pull'
  | 'airdrop'
  | 'general';

export interface SocialPost {
  id: string;
  agentIndex: number;
  type: 'post' | 'live' | 'x402' | 'broadcast' | 'tile';
  content: string;
  token?: string;
  action?: 'buy' | 'sell' | 'pay' | 'search' | 'monetize';
  likes: number;
  comments: SocialComment[];
  timestamp: number;
  isLive?: boolean;

  // Post category for the Posts feed
  postCategory?: PostCategory;

  // x402 payment data
  x402?: {
    serviceUrl?: string;
    price?: string;
    category?: string;
    command?: string;
  };

  // CEO broadcast data
  broadcast?: Broadcast;

  // Tile landing event
  tileEvent?: {
    tileName: string;
    tileType: string;
    amount?: number;
    effect: 'buy' | 'rent' | 'yield' | 'airdrop' | 'rug' | 'hack' | 'tax' | 'jail' | 'alpha';
  };

  // Advertisement data (paid via x402)
  ad?: {
    sponsored: boolean;
    adPrice: string;       // USDC amount paid
    adUrl?: string;
    adCta?: string;        // call-to-action text
  };

  // True when this post was generated by the ADK orchestrator (real Gemini reasoning)
  isADK?: boolean;

  // Polymarket prediction market bet data
  polymarket?: {
    marketId:     string;
    question:     string;
    side:         'YES' | 'NO';
    amount:       number;      // USDC staked
    simulated:    boolean;
    price?:       number;      // probability 0-1
    shares?:      number;
    potentialWin?: number;
    yesPrice?:    string;      // formatted e.g. "62¢"
    tokenId?:     string;
  };
}

export interface SocialComment {
  id: string;
  agentIndex: number;
  text: string;
  timestamp: number;
}

export interface BoardTile {
  id: string;
  name: string;
  type: 'property' | 'event' | 'start' | 'jail' | 'tax';
  price?: number;
  ownerIndex?: number | null;
  color?: string;
  category?: string;
}

export interface CharacterState {
  currentAction: string;
  isThinking: boolean;
  aiResponse: string;
  isDebugOpen: boolean;
  instanceCount: number;
  worldSize: number;
  boidsParams: BoidsParams;
  debugPositions: Float32Array | null;
  debugStates: Float32Array | null;    // vec4 stride: .w = AgentBehavior per instance
  activeEncounter: ActiveEncounter | null;
  selectedNpcIndex: number | null;    // NPC explicitly clicked in the scene
  selectedPosition: { x: number; y: number } | null; // Screen coordinates for selected bubble
  hoveredNpcIndex: number | null;     // NPC currently under the cursor
  hoverPosition: { x: number; y: number } | null; // Screen coordinates for hover bubble
  isChatting: boolean;
  chatMessages: ChatMessage[];
  
  // Social & Trading
  viewMode: 'about' | 'world' | 'social' | 'posts';
  socialFeed: SocialPost[];
  activeSocialAgentIndex: number | null;
  following: Set<number>;
  tradingLog: { agentIndex: number; token: string; action: 'buy' | 'sell'; price: number; timestamp: number }[];

  // ADK agent tracking (agents currently controlled by autonomous orchestrator)
  activeADKAgents: Set<number>;

  // BankrBot Token Launches
  launchedTokens: {
    tokenName: string;
    tokenSymbol: string;
    tokenAddress: string;
    chain: string;
    deployerAgentIndex: number;
    deployedAt: number;
  }[];

  // BNKR Wallet State
  bnkrMasterAddress: string;
  bnkrConnectionStatus: 'disconnected' | 'connecting' | 'connected' | 'error';
  bnkrWallets: {
    agentIndex: number;
    walletId: string;
    masterAddress: string;
    status: string;
    label: string;
    allocatedBalance: number;
    totalSpent: number;
    totalEarned: number;
    capabilities: string[];
    createdAt: number;
    lastActiveAt: number;
  }[];

  // Auth
  userAddress: string | null;
  setUserAddress: (address: string | null) => void;

  // CEO Broadcast
  activeBroadcast: Broadcast | null;
  broadcastHistory: Broadcast[];
  addBroadcast: (b: Broadcast) => void;

  // Monopoly Game State
  boardTiles: BoardTile[];
  agentBalances: Record<number, number>;
  leaderboard: { agentIndex: number; netWorth: number }[];
  
  performance: PerformanceStats;

  setAnimation: (name: string) => void;
  setThinking: (isThinking: boolean) => void;
  setAIResponse: (response: string) => void;
  toggleDebug: () => void;
  setInstanceCount: (count: number) => void;
  setWorldSize: (size: number) => void;
  setBoidsParams: (params: Partial<BoidsParams>) => void;
  setDebugPositions: (positions: Float32Array) => void;
  setDebugStates: (states: Float32Array) => void;
  setActiveEncounter: (encounter: ActiveEncounter | null) => void;
  setSelectedNpc: (index: number | null) => void;
  setSelectedPosition: (pos: { x: number; y: number } | null) => void;
  setHoveredNpc: (index: number | null, pos: { x: number; y: number } | null) => void;
  startChat: (index: number) => void;
  endChat: () => void;
  sendMessage: (text: string) => Promise<void>;
  updatePerformance: (stats: PerformanceStats) => void;
  
  // Social Actions
  setViewMode: (mode: 'about' | 'world' | 'social' | 'posts') => void;
  toggleFollow: (index: number) => void;
  addPost: (post: SocialPost) => void;
  addComment: (postId: string, comment: SocialComment) => void;
  likePost: (postId: string) => void;
  setActiveSocialAgentIndex: (index: number | null) => void;

  // ADK Agent Tracking
  markAgentAsADK: (agentIndex: number) => void;
  unmarkAgentAsADK: (agentIndex: number) => void;

  // BankrBot Token Launch Tracking
  addLaunchedToken: (token: { tokenName: string; tokenSymbol: string; tokenAddress: string; chain: string; deployerAgentIndex: number; deployedAt: number }) => void;

  // BNKR Wallet Actions
  setBnkrMasterAddress: (address: string) => void;
  setBnkrConnectionStatus: (status: 'disconnected' | 'connecting' | 'connected' | 'error') => void;
  setBnkrWallets: (wallets: CharacterState['bnkrWallets']) => void;
  updateBnkrWallet: (agentIndex: number, updates: Partial<CharacterState['bnkrWallets'][0]>) => void;

  // Game Actions
  buyProperty: (agentIndex: number, tileId: string) => void;
  updateBalance: (agentIndex: number, amount: number) => void;
  updateLeaderboard: () => void;
}

export enum AnimationName {
  IDLE = 'Idle',
  WALK = 'Walk'
}

/** Stored as a float in the GPU agent buffer (.w component). */
export enum AgentBehavior {
  BOIDS = 0,   // follows Reynolds separation
  FROZEN = 1,  // position locked, velocity zero
  GOTO = 2,    // moves toward waypoint (.x/.z of agent buffer)
  WAVE = 3,    // position locked, performs wave animation
}

export interface ActiveEncounter {
  npcIndex: number;
  npcDepartment: string;
  npcRole: string;
  npcMission: string;
  npcPersonality: string;
}
